# .streamlit/secrets.toml

[angelone]
api_key = "bJQupezI"
client_id = "DEDA1074"
pin = "2580"

# This is the long text token you got when scanning the QR code
totp_secret = "K3IVTSCIT3NWSLZ2Y3LQDW774I"